services:
  # Service 1 : L'entrée
  gateway:
    build: ./gateway
    image: mdevillet31/gateway
    dns:
      - 8.8.8.8
    ports:
      - "8080:5000"
    depends_on:
      - storage
    networks:
      - ton_reseau_devops

  # Service 2 : La logique de stockage
  storage:
    build: ./storage
    image: mdevillet31/storage
    dns:
      - 8.8.8.8
    depends_on:
      - db
    networks:
      - ton_reseau_devops

  # Service 3 : Stockage vectoriel
  qdrant-server:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    networks:
      - ton_reseau_devops

  # Service 4 : Ollama
  ollama-server:
    image: ollama/ollama:latest
    dns:
      - 8.8.8.8
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ton_reseau_devops

  # Service 5 : Chatbot
  chatbot:
    build: ./chat_bot
    dns:
      - 8.8.8.8
    ports:
      - "5002:5002"
    environment:
      - OLLAMA_HOST=http://ollama-server:11434
      - GEMINI_API_KEY=AIzaSyDN0SQfdc6npqmcniMkD8FBlzx2Itp7scA
    depends_on:
      - qdrant-server
      - ollama-server
      - db
    networks:
      - ton_reseau_devops

  # Service 6 : La base de données SQL
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: capsule_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - ton_reseau_devops

volumes:
  ollama_data:

networks:
  ton_reseau_devops:
    driver: bridge
