services:
  # Service 1 : L'entrée
  gateway:
    build: ./gateway
    image: mdevillet31/gateway
    dns:
      - 8.8.8.8
    ports:
      - "8080:5000"
    depends_on:
      - storage
    networks:
      - ton_reseau_devops

  # Service 2 : La logique de stockage
  storage:
    build: ./storage
    image: mdevillet31/storage
    dns:
      - 8.8.8.8
    networks:
      - ton_reseau_devops

  # Service 3 : Stockage vectoriel
  qdrant-server:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage:z
    networks:
      - ton_reseau_devops

  # Service 4 : Ollama
  ollama-server:
    image: ollama/ollama:latest
    dns:
      - 8.8.8.8
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ton_reseau_devops
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Service 5 : Chatbot
  chatbot:
    build: ./chat_bot
    dns:
      - 8.8.8.8
    environment:
      - OLLAMA_HOST=http://ollama-server:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - qdrant-server
      - ollama-server
    networks:
      - ton_reseau_devops
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  ollama_data:
  postgres_data:

networks:
  ton_reseau_devops:
    driver: bridge
  
